### ISSUE TITLE
Registering ARS-UI_Ramb_v2.0 Genome

### ISSUE THREAD

**Issue by edicliuyang** [Bioconductor/GenomeInfoDb#100]
Hi,

Would you help to add the [GCF_016772045.1_ARS-UI_Ramb_v2.0 genome]((https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_016772045.1/) ) to registered assemblies list?

We run into the following error when running forgeBSgenomeDataPkg. Thanks!

Error in .make_Seqinfo_from_genome(genome) : 
  "ARS-UI_Ramb_v2" is not a registered NCBI assembly or UCSC genome (use registered_NCBI_assemblies()
  or registered_UCSC_genomes() to list the NCBI or UCSC assemblies/genomes currently registered in the
  GenomeInfoDb package)

Best,
Yang

**Comment by hpages** [comment]
See https://github.com/Bioconductor/BSgenomeForge/issues/34#issuecomment-1718445966

**Comment by edicliuyang** [comment]
Hi Herve,

Thanks for the quick response! When I run the code above, I encounter this
error. Is there a way to solve this problem?

forgeBSgenomeDataPkgFromNCBI("GCF_016772045.1",                             
                                                          pkg_maintainer="Jane Doe ***@***.***>",                             
                                                          organism="ARSUIRambv2",
                                                          circ_seqs=character(0))


Error in .sort_and_rename_fasta_sequences(dna, assembly_accession) :  number of sequences in FASTA file does not match number of sequences in 'getChromInfoFromNCBI("GCF_016772045.1")'



Best,

Yang

**Comment by hpages** [comment]
Oops... indeed!

The [assembly report for `GCF_016772045.1`](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/016/772/045/GCF_016772045.1_ARS-UI_Ramb_v2.0/GCF_016772045.1_ARS-UI_Ramb_v2.0_assembly_report.txt) has some peculiarities not seen before (NAs in the `RefSeqAccn` column) that break some of the sanity checks performed internally by `forgeBSgenomeDataPkgFromNCBI()`.

This should be fixed in **BSgenomeForge** 1.2.1 (BioC release) and 1.3.1 (BioC devel). See https://github.com/Bioconductor/BSgenomeForge/commit/ad1a4896cff13309e05a70266c3282b03a4de0da Both versions should become available via `BiocManager::install()` in the next couple of days.

Also please note that:
- For the `organism` argument, the recommendation is to supply the _binomial name_ of the species. So `"Ovis aries"` in this case.
- According to the assembly report, `MT` is a circular sequence.

So:
```
forgeBSgenomeDataPkgFromNCBI("GCF_016772045.1",
                             pkg_maintainer="Jane Doe <janedoe@gmail.com>",
                             organism="Ovis aries",
                             circ_seqs="MT")
```
should work (with **BSgenomeForge** 1.2.1 or 1.3.1) and produce the **BSgenome.Oaries.NCBI.ARSUIRambv2.0** package in the current directory.

Cheers,
H.

**Comment by edicliuyang** [comment]
Awesome, thanks for the effort and suggestion. I will update you again a
couple of days later.

**Comment by hpages** [comment]
Did this work for you with the lastest **BSgenomeForge**?

**Comment by edicliuyang** [comment]
Sorry for the delay. Yes, it works for me with the latest BSgenomeForge
version.
