### ISSUE TITLE
download and parsing error in function call getChromInfoFromUCSC(genome = "hg19")

### ISSUE THREAD

**Issue by maximilian-leitheiser** [Bioconductor/GenomeInfoDb#104]
Hello!

For me (GenomeInfoDb_1.38.5), the function call `GenomeInfoDb::getChromInfoFromUCSC(genome = "hg19")` results in the error 'cannot open URL 'https://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/chromInfo.txt.gz''.

The mentioned URL is also not accessible for me in the browser.

However, the alternative 'https://hgdownload-euro.soe.ucsc.edu/goldenPath/hg19/database/chromInfo.txt.gz' can be downloaded manually and through `getChromInfoFromUCSC(genome = "hg19", goldenPath.url = "hgdownload-euro.soe.ucsc.edu/goldenPath") `. Unfortunately, then a parsing error occurs further downstream:

```
Error in .order_seqlevels(chrom_sizes[, "chrom"]) : 
  length(idx1) == length(ASSEMBLED_MOLECULES) is not TRUE
```

This seems to stem from the fact that ASSEMBLED_MOLECULES in hg19.R includes 'chrMT' while the downloaded file does not.

Thanks and best regards,
Max

**Comment by hpages** [comment]
Who maintains `hgdownload-euro.soe.ucsc.edu`? The `chromInfo.txt.gz` file at https://hgdownload-euro.soe.ucsc.edu/goldenPath/hg19/database/ is from 2009, which is way outdated!

In 2020 the UCSC folks made a massive change to `hg19`. It went from being based on `GRCh37` to being based on `GRCh37.p13`. This added hundreds of sequences to it!

`getChromInfoFromUCSC("hg19")` calls the [hg19.R script](https://github.com/Bioconductor/GenomeInfoDb/blob/devel/inst/registered/UCSC_genomes/hg19.R) which does some internal sanity checks to make sure that the genome contains the expected number of assembled molecules. In the case of the oudated `hg19` genome hosted at `hgdownload-euro.soe.ucsc.edu`, these check fails. Which is good!

You might want to contact the maintainers of the `hgdownload-euro.soe.ucsc.edu` mirror about this.

BTW it looks like `GenomeInfoDb::getChromInfoFromUCSC("hg19")` is working again. They had a power outage due to weather conditions in Santa Cruz that put the `hgdownload.cse.ucsc.edu` server down. See https://groups.google.com/a/soe.ucsc.edu/g/genome/c/zxS5jah4eZo/m/Jxuprb9BAQAJ

Note that `hgdownload.cse.ucsc.edu` is deprecated in favor of `hgdownload.soe.ucsc.edu`. FYI the latest version of **GenomeInfoDb** (1.38.6) is using the new URL. You should be able to get this new version via `BiocManager::install()` in the next 24 hours or so.

Best,
H.
