### ISSUE TITLE
Utilize UCSC REST API to retrieve Seqinfo

### ISSUE THREAD

**Issue by sanchit-saini** [Bioconductor/GenomeInfoDb#16]
hello,

As UCSC REST API is now available, there might be an opportunity to update the method of retrieving Seqinfo from UCSC for better maintainability.

Currently, Seqinfo is retrieved by download a file from UCSC goldenPath and later processed with a `read.table()`.
With the UCSC REST API Seqinfo could also be retrieved however it is going to requires a JSON parsing library(something like jsonlite) as a dependency.

Example : [http://api.genome.ucsc.edu/list/chromosomes?genome=mm9](http://api.genome.ucsc.edu/list/chromosomes?genome=mm9)

What do you all think about this?

**Comment by hpages** [comment]
Hi @sanchit-saini,

The `chromInfo.txt.gz` files downloaded by `getChromInfoFromUCSC()` (the workhorse behind `Seqinfo(genome=my_genome))`) are compressed. Can the data be retrieved in a compressed form with the UCSC REST API?

Thanks,
H.

**Comment by sanchit-saini** [comment]
Hi @hpages,
No, there is no option to retrieve data in compressed form from the UCSC API according to API 
reference:http://genome.ucsc.edu/goldenPath/help/api.html

Thanks!

**Comment by hpages** [comment]
Thanks for the link. Unfortunately this doesn't make the move from direct file download to download via the UCSC REST API appealing, as it would result in a performance regression. Maybe in the future when they support compressed data transfer.

H.

**Comment by lawremi** [comment]
Is the seqinfo data really that large? A simple benchmark may be informative. Depending on the official REST API would be more robust than relying on a file sitting in an FTP archive.

**Comment by hpages** [comment]
Some genomes (e.g. panTro5) have tens of thousands of scaffolds and no compression means downloading 1.3M of data instead of 218K (that's in the case of panTro5), i.e. 6x more data. The direct download has proven robust and fast so it's not clear that there is anything to win by replacing it with something less efficient that will also introduce new deps. This is a case where I'd say "if it ain't broke, don't fix it".

Maybe the REST API is something you want to try for the Table Browser in **rtracklayer** Michael? (`ucscTableQuery`/`getTable`) I remember the current implementation not being very reliable a couple of years ago when `makeTxDbFromUCSC()` was using it internally to download track data (`makeTxDbFromUCSC()` has switch to direct SQL queries since then).

**Comment by lawremi** [comment]
I understand that there are tradeoffs. Sanchit has already reimplemented the rtracklayer table query interface (pull request just pending some man page updates), so we thought we could give SeqinfoDb the same treatment.
