### ISSUE TITLE
Registration request for Patiria miniata NCBI assembly

### ISSUE THREAD

**Issue by andradejon** [Bioconductor/GenomeInfoDb#24]
I'd like to have the genome for Patiria miniata registered for the purpose of forging a BSgenome package. The assembly is ASM1570657v1 (Pmin_3.0) and below is the link to the NCBI page:

https://www.ncbi.nlm.nih.gov/assembly/GCF_015706575.1/

Let me know if there's anything I can clear up or help with. Thank you very much.

**Comment by hpages** [comment]
Hi,

I anticipated your request and added this yesterday. See commit 62a2e8673700411c0a650bf0476142b57764d6a9.

This is in **GenomeInfoDb** 1.27.12 which is part of BioC 3.13 (requires R 4.1). **GenomeInfoDb** 1.27.12 will become available to BioC 3.13 users via `BiocManager::install()` in the next 24 hours or so.

Note that BioC 3.13 is still officially in development but you can already install and use it if you have R 4.1. It will be officially released next week. See https://bioconductor.org/developers/release-schedule/

Cheers,
H.

**Comment by truong128** [comment]
Hi Admin and all colleges

I'd like to add this Akata genome "https://www.ncbi.nlm.nih.gov/nuccore/KC207813.1/" into the GenomeInfoDb to forge a BSgenome package. I really appreciate it if anyone please help to add it or show me how to add it. Thanks a lot.

Truong

**Comment by hpages** [comment]
@truong It's a really bad idea to ask your question in an issue that was closed 3 years ago, especially since your request is different from the original request of this issue.

Please take a look at the **BSgenomeForge** package [here](https://bioconductor.org/packages/BSgenomeForge) for how to forge a BSgenome data package for your NCBI assembly. Note that the assembly does not need to be registered in the **GenomeInfoDb** package for that.

If you need further help with this, please ask on the [Bioconductor support site](https://support.bioconductor.org/) or open an issue in the **BSgenomeForge** issue tracker [here](https://github.com/Bioconductor/BSgenomeForge/issues).

Best,
H.

**Comment by truong128** [comment]
Hi H.

Thank you very much for your help. I appreciate that.
